# Generated by Django 2.2.3 on 2019-07-23 20:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yachts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rentals',
            new_name='Rental',
        ),
        migrations.RenameModel(
            old_name='Yachts',
            new_name='Yacht',
        ),
    ]
